### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by ynezz**

### CODE REVIEW

**Comment by enotodden** [comment]
Hi @ynezz ! Thanks for your pull request!

I've taken a look at this and there seems to be no need for all this timeout logic. I've briefly talked to John, who develops Turbo and he agrees. IOStream:close should not block. And even if it did, you never set self.disconnect_timeout_ref so the timeout callback is never called anyway. I'm assuming this is a mistake, since you're setting self.connect_timeout_ref.
Also the close callback is never set so the caller's callback will never be run on a successful close of the socket.
Please correct me if I misunderstood something here.
I obviously agree that we should have a way of closing the connection a turboredis.Connection uses, but if I can get away with a simple stream:close(), I'd rather do that.

The error handling after the call to new_nonblock_socket() is great though :+1

**Comment by enotodden** [comment]
I have added a disconnect() function in 1635f4ef8b4feb17acd3a5a295665475eac8aa2c and added your error handling for new_nonblock_socket()

**Comment by ynezz** [comment]
Hi,

this commit https://github.com/ynezz/turboredis/commit/b8881c96b22acf07059879e8e895c911ee6b7f2f fixed the missing self reference for connect_timeout (connect_timeout vs self.connect_timeout), which I assume is [still wrong in the master (https://github.com/enotodden/turboredis/blob/master/turboredis/connection.lua#L62).

I wasn't sure if the disconnect() could block, so I've added the timeout for disconnect also.

Thanks and keep up the good work!

**Comment by ynezz** [comment]
And just a small nitpick, this [timeout variable](https://github.com/enotodden/turboredis/blob/master/turboredis/connection.lua#L61) should be probably local.

**Pull request closed without merging**
